accounts:
  - name: acMain
    coins: ["2499000000alteredCarbon"]
  - name: acValidator1
    coins: ["1000000alteredCarbon"]
  - name: preSaleFaucet
    coins: ["1000000alteredCarbon"]
validator:
  name: acValidator1
  staked: "1000000alteredCarbon"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: preSaleFaucet
  coins: ["100alteredCarbon"]
  coins_max: ["100alteredCarbon"]
  port: 4500
genesis:
  app_state:
    staking:
      params:
        bond_denom: "alteredCarbon"