accounts:
  - name: acMain
    coins: ["2499000000alteredCarbon"]
  - name: acValidator1
    coins: ["1000000alteredCarbon"]
validator:
  name: acValidator1
  staked: "1000000alteredCarbon"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "alteredCarbon"
    crisis:
      constant_fee:
        denom: "alteredCarbon"
    gov:
      deposit_params:
        min_deposit:
          - "amount": "10000000"
            "denom": "alteredCarbon"
    mint:
      params:
        mint_denom: "alteredCarbon"
        inflation_max: "0"
        inflation_min: "0"